repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        args: ['--skip-string-normalization', '--line-length', '79']

  - repo: 'https://github.com/PyCQA/flake8'
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-isort
        name: flake8
        entry: flake8
        #exclude: '^(?!versions/)'
        files: ^(bot/|core/|src/)
        language: python
        types: [python]
        args: ['--max-line-length=79']

  - repo:  'https://github.com/PyCQA/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        entry: isort
        #exclude: '^(?!versions/)'
        files: ^(bot/|core/|src/)
        language: system
        types: [python]
